### PR TITLE
log window optimize

### PR DESCRIPTION
**Pull request by copyliu**
layoutSpecialScrollable (the log) now measures character size directly instead of rendering to image to get size, the log in CJK version can show up in seconds now!

### CODE REVIEW

**Comment by copyliu** [comment]
hmm, don't merge. it seems break something, just close it util fixed

**Comment by vit9696** [comment]
Thanks for the patch. This looks pretty promising, will be looking forward to an improved version.

**Comment by copyliu** [comment]
fix an infinite loop, not tested well but it seems good

**Comment by vit9696** [comment]
Thanks. We reviewed it with @knox-umineko and found no obvious issues. Pretty decent work. Merged in master with minor codestyle changes.

I also removed std::set_terminate change, as it seemed to be accidental and did not seem right (no abort in the end, strange macro guarding, etc.). If you want that added, I believe we should discuss it in a separate patch.

**Comment by copyliu** [comment]
also pick https://github.com/copyliu/onscripter-ru/commit/25ded46e16eb2c8e23bdc3fb392c1095238c817c revert that change, it isn't an engine issue.

**Comment by vit9696** [comment]
Right, will double-check and do that after CI completes the build.

**Pull request closed without merging**
